Porting SettingsControls
CommunityToolkit/Windows pull request #154
Opened 2023-07-19 19:14 UTC by niels9001

2023-07-19 20:11 UTC, Arlodotexe commented on components/SettingsControls/src/AdditionalAssemblyInfo.cs
> +// used with the Labs infrastructure.
```suggestion
// used with the Toolkit infrastructure.
```

2023-07-19 20:12 UTC, Arlodotexe approved these changes

2023-07-19 22:26 UTC, michael-hawker commented
@Arlodotexe even weird CI issues here...?

2023-07-19 22:31 UTC, michael-hawker requested changes
Couple of small things to fix.

No code changes, just the namespace right?

2023-07-19 22:31 UTC, michael-hawker commented on components/SettingsControls/samples/Assets/SettingsCard.png
If we don't have an icon for this one yet, can we at least get a better default to start using? 😋

2023-07-19 22:31 UTC, michael-hawker commented on components/SettingsControls/src/Dependencies.props
> +  </ItemGroup>
Ah, this is the CI issue, you don't need a package reference anymore, just need to add a project reference in the csproj to the Triggers project.

(Don't add a thing in the root props file like was done elsewhere, just use the path in the project reference in the csproj. Though we had an example somewhere, but can't find it atm)

2023-07-20 15:01 UTC, merged

2023-07-20 20:50 UTC, michael-hawker reviewed
🦙❤