Fix: StaggeredLayout division bug
CommunityToolkit/Windows pull request #574
Opened 2024-11-28 03:08 UTC by Poker-sang

## Fixes

closes #542 
fix <https://github.com/microsoft/PowerToys/pull/35139>

## PR Type

What kind of change does this PR introduce?

## What is the current behavior?

## What is the new behavior?

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [x] Tested code with current supported SDKs
- [ ] New component
  - [ ] Documentation has been added
  - [ ] Sample in sample app has been added
  - [ ] Analyzers are passing for documentation and samples
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (if applicable)
- [ ] Header has been added to all new source files
- [x] Contains **NO** breaking changes

## Other information

2024-11-28 07:23 UTC, michael-hawker commented
Not sure what happened with the tooling submodule here either.

Wondering if we could add a test for anything around this to help guard future issues?

2024-12-02 22:15 UTC, michael-hawker approved these changes
🦙❤️ Thanks!

2024-12-02 22:26 UTC, michael-hawker requested changes
Was just about to approve and merge, but noticed it was slightly different than when I had first looked before the weekend. Thanks for fixing the tooling submodule stuff.

2024-12-02 22:26 UTC, michael-hawker commented on components/Primitives/src/StaggeredLayout/StaggeredLayout.cs
> +            numColumns = Math.Max(1, (int)Math.Floor(availableWidth / (DesiredColumnWidth + ColumnSpacing)));
Oh @Poker-sang just noticed, originally this was just `columnWidth` from above, should we still be using that as it does the NaN check? 

We'd just move the `ColumnSpacing` as part of that value on 165? I guess that was missing before? (Maybe it'd be better to move that add of the ColumnSpacing change to #573, and just keep this change to be the fix for the change from `state.`?) Then it's easy to approve the variable substitution here quick for the crash, and we can just re-validate the other behavior changes all within #573 together?

2024-12-03 02:18 UTC, Poker-sang commented
Ok reverted it. i commit this before because i found that we forget to calculate spacing before. And we might see the bug clearly when `ColumnSpacing` is close to `DesiredColumnWidth`. And you are right we should make it to #573

2024-12-03 20:01 UTC, michael-hawker approved these changes

2024-12-03 20:16 UTC, michael-hawker commented
🎉 Thanks @Poker-sang for this quick fix! 🦙❤️ And for moving the column fix to the other PR. I'll get this merged once the CI passes, some strange issue I haven't seen before there; so just re-kicking to see if it was just a stray cosmic ray! 🤞

2024-12-03 20:57 UTC, merged